### ISSUE TITLE
Is it possible to extend the default annotation processor for spring data jdbc to additionally generate q classes for  classes  with other annotation rather than only for classes that use the Id annotation?

### ISSUE THREAD

**Issue by matevskial** [infobip/infobip-spring-data-querydsl#104]
Consider the example from your `Mapped collections` section of your README: https://github.com/infobip/infobip-spring-data-querydsl?tab=readme-ov-file#mappedcollection-support

```java
public record Student(
        @Id
        Long id,

        String name,

        @MappedCollection(idColumn = "StudentId", keyColumn = "CourseId")
        Set<StudentCourse> courses
) {

   void addItem(Course course) {
      var studentCourse = new StudentCourse(null, AggregateReference.to(course.id()), null);
      courses.add(studentCourse);
   }

}
```

```java
public record Course(
        @Id
        Long id,
        String name
) {

}
```

```java
public record StudentCourse(
        AggregateReference<Course, Long> courseId,

        Long studentId
) {

}
```

**Note that StudentCourse does not have a  separate id column(Let's say the real primary key on the database level is a composite key with courseId and studentId.**

The annotation processor would generate q classes for each entity that has the `@Id` annotation.

Is it possible to easily **extend** the annotation processor to support this behavior :  `generate q classes for classes that use @Id annotation or for classes that use other annotation such as the querydsl's @QueryEntity`?

```java
@QueryEntity
public record StudentCourse(
        AggregateReference<Course, Long> courseId,

        Long studentId
) {

}
```

**Comment by lpandzic** [comment]
It's doable, but this code path needs to be coded in in the annotation processor. All I can suggest is write a test and start from there. I don't think it would be too difficult - you have tests for each part of the flow - Q class generation and separate tests for interactions with a specific data module.

**Comment by matevskial** [comment]
Are you suggesting that I should modify the annotation processor itself(located in this repo) or I am able to extend it with a code that I would write in my own project?

**Comment by lpandzic** [comment]
Both should be possible.

**Comment by matevskial** [comment]
Can you give me pointers for the option to write custom code that extends the annotation processor to take into account custom annotations too and not only the `@ID` annotation?

I've tried this

`java
@AutoService(Processor.class)
public class CustomSpringDataJdbcAnnotationProcessor extends SpringDataJdbcAnnotationProcessorBase {

  public CustomSpringDataJdbcAnnotationProcessor() {
    super(CustomNamingStrategy.class);
  }

  @Override
  public Set<String> getSupportedAnnotationTypes() {
    Set<String> annotationTypes = new HashSet<>(super.getSupportedAnnotationTypes());
    annotationTypes.add(Table.class.getName());
   return Set.copyOf(annotationTypes);
  }
}
`
But it seems that the annotation processor still only takes into an account only the `@ID` annotation.
What am I missing?

**Comment by matevskial** [comment]
Update: I managed to write custom annotation processor that extends  `SpringDataJdbcAnnotationProcessorBase` and generates **entity** Q classes for classes annotated with some other annotation(I've chosen querydsl's `QueryEntity` annotation).

```java
@AutoService(Processor.class)
public class CustomSpringDataJdbcAnnotationProcessor extends SpringDataJdbcAnnotationProcessorBase {

  private RoundEnvironment roundEnv;

  public CustomSpringDataJdbcAnnotationProcessor() {
    super(CustomSpringDataJdbcQuerydslNamingStrategy.class);
  }

  @Override
  public Set<String> getSupportedAnnotationTypes() {
    Set<String> annotationTypes = new HashSet<>(super.getSupportedAnnotationTypes());
    annotationTypes.add(QueryEntity.class.getName());
    return Set.copyOf(annotationTypes);
  }

  @Override
  protected Configuration createConfiguration(RoundEnvironment roundEnvironment) {
    this.roundEnv = roundEnvironment;
    DefaultConfiguration configuration = (DefaultConfiguration) super.createConfiguration(roundEnvironment);
    configuration.setAlternativeEntityAnnotation(QueryEntity.class);
    return configuration;
  }

  @Override
  protected Set<TypeElement> collectElements() {
    var entityElements = roundEnv.getElementsAnnotatedWith(QueryEntity.class)
        .stream()
        .filter(element -> element instanceof TypeElement)
        .map(element -> (TypeElement) element)
        .collect(Collectors.toSet());

    Stream<TypeElement> entityElementsIncludingEmbeddedEntities = entityElements.stream()
        .flatMap(this::getEntityElementWithEmbeddedEntities);

    return Stream.concat(super.collectElements().stream(), entityElementsIncludingEmbeddedEntities).collect(Collectors.toSet());
  }

  private Stream<TypeElement> getEntityElementWithEmbeddedEntities(TypeElement entityElement) {
    var types = processingEnv.getTypeUtils();
    var embeddedElements = ElementFilter.fieldsIn(entityElement.getEnclosedElements())
        .stream()
        .filter(enclosedElement -> Objects.nonNull(
            enclosedElement.getAnnotation(Embedded.class)))
        .map(element -> types.asElement(element.asType()))
        .filter(element -> element instanceof TypeElement)
        .map(element -> (TypeElement) element)
        .collect(Collectors.toSet());
    return Stream.concat(Stream.of(entityElement), embeddedElements.stream());
  }
}
```

And it seems to be working.

But I have some issues with this implementation of the solution:

- I copied the implementation of `collectElements` from the base class. I probably shouldn't do this
- I also copied the private method for collecting the embedded elements. Shouldn't do this too
- I overrided  `getSupportedAnnotationTypes`  and  I am not sure what is the purpose of  that method.(I tested even without overriding this method and seems it's still working)

But I think we can do better to make the process of extending annotation processor easier and cleaner.
Essentially, we should be able to change `SpringDataJdbcAnnotationProcessorBase`  so we can add additionally entity annotations.

I have some ideas for changes:

- Add a protected method `getAdditionalEntityAnnotations` that can be ovveridden by custom annotation processor
- Change `createConfiguration`  in  `SpringDataJdbcAnnotationProcessorBase` to add the additional entity annotations so we don't need to override this method like I did above.
- Change method `collectElements` in  `SpringDataJdbcAnnotationProcessorBase` to use ` roundEnv.getElementsAnnotatedAny(conf.getEntityAnnotations())`

After these changes, one should write this code in order to extend the annotation processor to support additional annotations for generating **entity** q classes:

```java
@AutoService(Processor.class)
public class CustomSpringDataJdbcAnnotationProcessor extends SpringDataJdbcAnnotationProcessorBase {

  private RoundEnvironment roundEnv;

  public CustomSpringDataJdbcAnnotationProcessor() {
    super(CustomSpringDataJdbcQuerydslNamingStrategy.class);
  }

  @Overrider
  public Set<Class<? extends Annotation>> getAdditionalEntityAnnotations() {
    return Set.of(QueryEntity.class);
  }
}
```

Let me know what you think?

**Comment by lpandzic** [comment]
That sounds reasonable, feel free to open up a PR.

**Comment by lpandzic** [comment]
I'm closing this one as stale - if you still need the functionality feel free to reopen and please provide a PR.
