### ISSUE TITLE
Support PagingAndSortingRepository of spring data jdbc

### ISSUE THREAD

**Issue by samotoo** [infobip/infobip-spring-data-querydsl#12]
Hi,

First of all, thank you for creating the great library, it makes dynamic query in spring-data-jdbc much more easily.

As of the current version (4.0.0), QuerydslJdbcRepository extends CrudRepository. There is PagingAndSortingRepository of spring-data-jdbc provides paging and sorting in addition to CrudRepository, so is it possible for QuerydslJdbcRepository to extends PagingAndSortingRepository so that we can leverage the full power of spring-data-jdbc?

Thanks again.

**Comment by lpandzic** [comment]
I've added support for PagingAndSortingRepository. I hope to release it soon.

**Comment by samotoo** [comment]
Fantastic! Looking forward to 4.1.0.

**Comment by lpandzic** [comment]
4.1.0 has been released. It should be available on Maven Central in a couple of hours (badge takes longer to update).
