### ISSUE TITLE
Gradle 6.x gives errors

### ISSUE THREAD

**Issue by hrandika** [infobip/infobip-spring-data-querydsl#13]
When we add the library with Gradle  

**compile 'com.infobip:infobip-spring-data-jdbc-querydsl:4.0.1-SNAPSHOT'**  

 Could not find querydsl-apt-4.3.1-jpa.jar (com.querydsl:querydsl-apt:4.3.1).
Searched in the following locations:
         file:/home/randika/.m2/repository/com/querydsl/querydsl-apt/4.3.1/querydsl-apt-4.3.1-jpa.jar

openjdk version "11.0.8" 2020-07-14 LTS
org.springframework.boot' version '2.3.4.RELEASE'

**Comment by lpandzic** [comment]
`4.0.1-SNAPSHOT`? 4.0.1-SNAPSHOT isn't released anywhere, why aren't you using 4.0.0 from Maven Central?
https://search.maven.org/artifact/com.querydsl/querydsl-apt/4.3.1/jar is available on Maven Central.

**Comment by lpandzic** [comment]
As this issue is not reproducible, I'm closing it. Feel free to reopen if you can provide more information.
