### ISSUE TITLE
Why my webflux application can not run after adding r2dbc  querydsl boot starter

### ISSUE THREAD

**Issue by kengan** [infobip/infobip-spring-data-querydsl#17]
I made  a webflux application and  support r2dbc.
Everything is  OK. The application can start  normally.
But after adding  "infobip-spring-data-r2dbc-querydsl-boot-starter", the application can not  be started. When I clicked run button in IDEA, after a  while the application stop  automatically.
Can you help  me. Thank you!

**Comment by lpandzic** [comment]
Hard to say without more info.
Does your application satisfy https://github.com/infobip/infobip-spring-data-querydsl#R2DBCRequirements?

**Comment by kengan** [comment]
I send you my webflux application
Can you help me check it? Thank you!




[webflux-db-demo.zip](https://github.com/infobip/infobip-spring-data-querydsl/files/6107896/webflux-db-demo.zip)

**Comment by kengan** [comment]
You  can remove the comment in pom.xml and use the infobip-spring-data-r2dbc-querydsl-boot-starter

**Comment by creativelikeadog** [comment]
I have the same issue even using flyway.

Spring: 2.4.2
querydsl: 4.4.0
infobip: 5.4.0

I'm using the autoconfiguration provided by spring to create Flyway bean, before when I was not trying to introduce querydsl everything was running fine, flyway is applying the migrations, even in tests I have a junit5 extension that uses flyway to clean the db and migrate after each test, and everything regarding flyway is setup fine.

Dependencies:
```dependencies {
	kapt("org.springframework.boot:spring-boot-configuration-processor")
	implementation("org.springframework.boot:spring-boot-starter-actuator")
	implementation("org.springframework.boot:spring-boot-starter-jdbc")
	implementation("org.springframework.boot:spring-boot-starter-data-r2dbc")
	implementation("org.springframework.boot:spring-boot-starter-security")
	implementation("org.springframework.boot:spring-boot-starter-validation")
	implementation("org.springframework.boot:spring-boot-starter-webflux")
	implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
	implementation("io.projectreactor.kotlin:reactor-kotlin-extensions")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor")
	implementation("org.flywaydb:flyway-core")
	runtimeOnly("io.r2dbc:r2dbc-postgresql")
	runtimeOnly("org.postgresql:postgresql")

	// query dsl
	implementation("org.springframework.data:spring-data-relational")
	implementation("com.querydsl:querydsl-apt:$queryDslVersion")
	implementation("com.querydsl:querydsl-sql:$queryDslVersion")
	implementation("com.infobip:infobip-spring-data-jdbc-annotation-processor:$infobipQueryDslVersion")
	implementation("com.infobip:infobip-spring-data-r2dbc-querydsl-boot-starter:$infobipQueryDslVersion")
	//
```
