### ISSUE TITLE
Spring + R2DBC + Flyway: bean of type 'com.querydsl.sql.SQLTemplates' that could not be found.

### ISSUE THREAD

**Issue by creativelikeadog** [infobip/infobip-spring-data-querydsl#29]
I have the same issue even using flyway.

```
    ***************************
    APPLICATION FAILED TO START
    ***************************

    Description:

    Parameter 0 of method querydslSqlConfiguration in com.infobip.spring.data.r2dbc.R2dbcConfiguration required a bean of type 'com.querydsl.sql.SQLTemplates' that could not be found.


    Action:

    Consider defining a bean of type 'com.querydsl.sql.SQLTemplates' in your configuration.
```

Spring: 2.4.2
querydsl: 4.4.0
infobip: 5.4.0

I'm using the autoconfiguration provided by spring to create Flyway bean, before when I was not trying to introduce querydsl everything was running fine, flyway is applying the migrations, even in tests I have a junit5 extension that uses flyway to clean the db and migrate after each test, and everything regarding flyway is setup fine.

Dependencies:
```dependencies {
	kapt("org.springframework.boot:spring-boot-configuration-processor")
	implementation("org.springframework.boot:spring-boot-starter-actuator")
	implementation("org.springframework.boot:spring-boot-starter-jdbc")
	implementation("org.springframework.boot:spring-boot-starter-data-r2dbc")
	implementation("org.springframework.boot:spring-boot-starter-security")
	implementation("org.springframework.boot:spring-boot-starter-validation")
	implementation("org.springframework.boot:spring-boot-starter-webflux")
	implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
	implementation("io.projectreactor.kotlin:reactor-kotlin-extensions")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor")
	implementation("org.flywaydb:flyway-core")
	runtimeOnly("io.r2dbc:r2dbc-postgresql")
	runtimeOnly("org.postgresql:postgresql")

	// query dsl
	implementation("org.springframework.data:spring-data-relational")
	implementation("com.querydsl:querydsl-apt:$queryDslVersion")
	implementation("com.querydsl:querydsl-sql:$queryDslVersion")
	implementation("com.infobip:infobip-spring-data-jdbc-annotation-processor:$infobipQueryDslVersion")
	implementation("com.infobip:infobip-spring-data-r2dbc-querydsl-boot-starter:$infobipQueryDslVersion")
	//
```

_Originally posted by @creativelikeadog in https://github.com/infobip/infobip-spring-data-querydsl/issues/17#issuecomment-823540709_

**Comment by lpandzic** [comment]
R2DBC doesn't support flyway out of the box (at least not until 2.5.0 release). How are you setting up flyway in your project?
This is how it is set up for tests in this project:
https://github.com/infobip/infobip-spring-data-querydsl/blob/master/infobip-spring-data-r2dbc-querydsl-boot-starter/src/test/java/com/infobip/spring/data/r2dbc/TestConfiguration.java
https://github.com/infobip/infobip-spring-data-querydsl/blob/master/infobip-spring-data-r2dbc-querydsl-boot-starter/src/test/resources/application.yaml

**Comment by creativelikeadog** [comment]
Ok, wiring the flyway by hand makes it work, but now I'm receiving `QuerydslR2dbcRepositoriesAutoConfigureRegistrar.EnableR2dbcRepositoriesConfiguration: Invocation of init method failed; nested exception is java.lang.NullPointerException`  

I'm using kotlin `data class` so all constructors have all arguments. not sure what else could it be =/

**Comment by creativelikeadog** [comment]
Apparently, there are 2 constructors, one with the named parameters, and one default created by kotlin, so the `QuerydslExpressionFactory` is getting the constructor based on the maximum size of parameters, but it gladly checks for a constructor with the annotation `PersistenceConstructor`, so I just needed to do:

```
@Table
data class Category @PersistenceConstructor constructor(
```

**Comment by lpandzic** [comment]
If you have time and will, please create a PR that fixes this for kotlin.

**Comment by creativelikeadog** [comment]
Oh, there is no fix to be done because using that annotation works fine, so maybe just put it in the README, something like: 
"if you are using kotlin please annotate the entities constructor with `@PersistenceConstructor`"

**Comment by lpandzic** [comment]
Ok but where does the selection code fail without `@PersistenceConstructor`? In spring-data or this project codebase?

**Comment by creativelikeadog** [comment]
What i'm talking about is this block of code here:
https://github.com/infobip/infobip-spring-data-querydsl/blob/master/infobip-spring-data-common/src/main/java/com/infobip/spring/data/common/QuerydslExpressionFactory.java#L49

```
private Constructor<?> getConstructor(Class<?> type) {
      Constructor<?>[] declaredConstructors = type.getDeclaredConstructors();
      Constructor<?> persistenceConstructor = Arrays.stream(declaredConstructors)
                                                    .filter(constructor -> constructor.isAnnotationPresent(
                                                            PersistenceConstructor.class))
                                                    .findAny()
                                                    .orElse(null);

      if (Objects.nonNull(persistenceConstructor)) {
          return persistenceConstructor;
      }

      return Arrays.stream(declaredConstructors)
                   .max(Comparator.comparingInt(Constructor::getParameterCount))
                   .orElse(null);
  }
```

So for kotlin applications, we must ensure that the entities constructor is annotated with `@PersistenceConstructor` unless, the last `return` statement will return the constructor with the max number of parameters, which from the kotlin generated bytecode is not the one where the parameters are named, instead is the generic one where the parameters are named like `arg0, arg1, arg2, arg3...`
