### ISSUE TITLE
How to customize projection query in the new version？

### ISSUE THREAD

**Issue by hgqapp** [infobip/infobip-spring-data-querydsl#31]
In the new version (5.4.0) because 
deprecated QuerydslJdbcFragment#query .
replaced by QuerydslJdbcFragment#queryOne and QuerydslJdbcFragment#queryMany,but it cannot customize projection.

And how to customize projection query?
Please help me.

**Comment by lpandzic** [comment]
The query method was undeprecated. Note however that query method relies on Querydsl infrastructure when handling ResultSet and JDBC and other rely on Spring Data infrastructure.
This might result in different behavior in some cases - the one I was primarily worried about was different timezone handling, details here - https://github.com/spring-projects/spring-data-jdbc/issues/986.

**Comment by lpandzic** [comment]
5.4.2 contains the fix.

**Comment by hgqapp** [comment]
> 5.4.2 contains the fix.

Ok i'm waiting, thanks.

**Comment by hgqapp** [comment]
Thanks for fix.

**Comment by hgqapp** [comment]
> The query method was undeprecated. Note however that query method relies on Querydsl infrastructure when handling ResultSet and JDBC and other rely on Spring Data infrastructure.
> This might result in different behavior in some cases - the one I was primarily worried about was different timezone handling, details here - [spring-projects/spring-data-jdbc#986](https://github.com/spring-projects/spring-data-jdbc/issues/986).

In my project
