### ISSUE TITLE
I can't run the test program.

### ISSUE THREAD

**Issue by lpn666** [infobip/infobip-spring-data-querydsl#34]
I can't run the test program, cause I got en error :   
`import static com.infobip.spring.data.r2dbc.QPerson.person;
import static com.infobip.spring.data.r2dbc.QPersonSettings.personSettings;`

I can't find these Class in the project, nor in maven rep.

**Comment by lpandzic** [comment]
Those classes aren't available in Maven Central repository. Those classes are only used as example domain classes in documentation and are available under test scope in respective modules in this repository.

**Comment by lpn666** [comment]
> Those classes aren't available in Maven Central repository. Those classes are only used as example domain classes in documentation and are available under test scope in respective modules in this repository.

but i can find these classes in the test scope.
![捕获](https://user-images.githubusercontent.com/26716574/123932121-b694fe80-d9c3-11eb-876c-42b01effa92d.PNG)

**Comment by lpandzic** [comment]
<img width="495" alt="Screenshot 2021-06-30 at 12 18 07" src="https://user-images.githubusercontent.com/4463380/123944251-3b205680-d99d-11eb-9889-0c1df02d73c2.png">
They are not in source code - they are generated. If you're in IDEA a simple build of the project should generate them through use of annotation processor which should be enabled in IDEA by default.
