### ISSUE TITLE
Embedded does not take prefix into account

### ISSUE THREAD

**Issue by dirkluijk** [infobip/infobip-spring-data-querydsl#46]
A while ago, support for `@Embedded` was added ([commit](https://github.com/infobip/infobip-spring-data-querydsl/commit/c7f048b8ef98112a404a019b29c5abd038d60fee)), however, it does not take the `prefix` into account.

Is this easy to fix?

**Comment by lpandzic** [comment]
Hi, what do you mean by prefix?
Can you share an example that does and doesn't work?

**Comment by lpandzic** [comment]
I'm closing this one due to staleness, feel free to reopen with more details @dirkluijk .
