### ISSUE TITLE
remove @Transactional(readOnly = true) from QuerydslJdbcRepository

### ISSUE THREAD

**Issue by AlekseiTokarev** [infobip/infobip-spring-data-querydsl#60]
After the recent library upgrade, my integration tests which call the save() method started failing with:
 `org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction`

Found that `@Transactional(readOnly = true)` was added to QuerydslJdbcRepository in  the following commit  https://github.com/infobip/infobip-spring-data-querydsl/commit/ead317f5fb782178913a90798c420be00c5f8e12#diff-20e913bdb291b1677a4ab45059b3989e660e2996d71033de31c7e1e62839d569R15

I understand that I could add @Transactional(readOnly = false) on top of each test but QuerydslJdbcRepository class is for all CRUD operations and shouldn't be defaulted to `readOnly=true`.

I'm proposing to delete that annotation to make the caller handle transactions when needed.

Note: `org.springframework.data.repository.CrudRepository` doesn't have any @Transactional.

**Comment by lpandzic** [comment]
Fixed in 6.2.2
