### ISSUE TITLE
support complex Sql

### ISSUE THREAD

**Issue by z7658329** [infobip/infobip-spring-data-querydsl#64]
i want to use this to replace  mybatis xml  SQL, does it support complex SQL,like: 

SELECT
	*
FROM
	(
		SELECT
			SUM(total) over (
				PARTITION BY date,

			IF (`rank` <= 3, `rank`, 4)
			) total,

		IF (`rank` <= 4, 1, 0) flag,
		date,
		id1,
		id2,
		id3,
		one,
		two,
		three,
		`end_point`,
		`rank`
	FROM
		(
			SELECT
				total,
				date,
				one,
				`two`,
				`three`,
				`id1`,
				`id2`,
				`id3`,
				`end_point`,
				ROW_NUMBER () over (
					PARTITION BY date
					ORDER BY
						total DESC
				) AS `rank`
			FROM
				(
					SELECT
						sum(VALUE) AS total,
						`date`,
						`one`,
						`two`,
						`three`,
						`id1`,
						`id2`,
						`id3`,
						`end_point`
					FROM
						xx.tableA
					WHERE
						1 = 1
					AND `date` BETWEEN ?
					AND ?
					AND uri =?
					AND line_type =?
					AND (1 = 0 OR b3_id IN(?))
					GROUP BY
						b3_id,
						`date`
				) t
		) t
	) t
WHERE
	flag = 1
ORDER BY
	date ASC,
	`rank` DESC

**Comment by lpandzic** [comment]
Yes, Querydsl does support such queries.

**Comment by z7658329** [comment]
> 

can you use querydsl to transalte this sql ?thanks

**Comment by lpandzic** [comment]
[Querydsl google group](https://groups.google.com/g/querydsl) or stackoverflow is a better place for this kind of questions.

**Comment by lpandzic** [comment]
Another option would be to go to https://github.com/querydsl/querydsl/discussions (I just found about it right now).
