### ISSUE TITLE
How to support one-to-many relationship for spring data jdbc

### ISSUE THREAD

**Issue by xjianyu** [infobip/infobip-spring-data-querydsl#65]
`@Table`
`@Getter`
`@Builder`
`@AllArgsConstructor`
`public class User  {`
 `   @Id private Long id;`
 `   private String username;`
  `  @Builder.Default private Set<RoleRef> roles = new HashSet<>();`
`}`

`@Table("user_role")`
`@Getter`
`@AllArgsConstructor`
`public class RoleRef {`
`    @Id private Long id;`
`    private AggregateReference<Role, Long> role;`
`    }`

`@Table`
`@Getter`
`@Builder`
`@AllArgsConstructor`
`public class Role {`
 `   @Id private Long id;`
`    @Column("role_name")`
`    private String roleName;`
`    }`

CREATE TABLE `user` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

CREATE TABLE `role` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `role_name` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

`user_role :`
CREATE TABLE `user_role` (
  `user` bigint(20) NOT NULL,
  `role` bigint(20) NOT NULL,
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

QUser class has 'roles' field, but table 'user'   no Column named 'roles'.
how to use innerJoin Query?

**Comment by tianyu94** [comment]
https://docs.spring.io/spring-data/jdbc/docs/current/reference/html/#jdbc.mybatis

https://github.com/spring-projects/spring-data-examples/tree/main/jdbc/mybatis

**Comment by lpandzic** [comment]
@xjianyu does this cover your question - https://github.com/infobip/infobip-spring-data-querydsl#JDBCInnerJoin?

**Comment by lpandzic** [comment]
If you're looking for code to try it out yourself - https://github.com/infobip/infobip-spring-data-querydsl/blob/master/infobip-spring-data-jdbc-querydsl/src/test/java/com/infobip/spring/data/jdbc/QuerydslJdbcRepositoryTest.java#L207.

**Comment by xjianyu** [comment]
> @xjianyu does this cover your question - https://github.com/infobip/infobip-spring-data-querydsl#JDBCInnerJoin?

I find this - https://github.com/infobip/infobip-spring-data-querydsl/issues/41#issue-995450241
the @MappedCollection not supported？

**Comment by lpandzic** [comment]
Hm, you didn't use `@MappedCollection` in original post. Can you maybe provide a small project that reproduces the issue you're having?

**Comment by xjianyu** [comment]
> Hm, you didn't use `@MappedCollection` in original post. Can you maybe provide a small project that reproduces the issue you're having?
ok, see - https://github.com/xjianyu/querydsl-jdbc-demo/blob/master/src/test/java/com/example/querydsljdbcdemo/QuerydslJdbcDemoApplicationTests.java

**Comment by lpandzic** [comment]
I've added basic support to 7.2.0 - details in README.md: https://github.com/infobip/infobip-spring-data-querydsl#MappedCollection.
Code is located here: https://github.com/infobip/infobip-spring-data-querydsl/tree/master/infobip-spring-data-jdbc-querydsl/src/test/java/com/infobip/spring/data/jdbc/mapped/collection.

**Comment by xjianyu** [comment]
@lpandzic I've tested it and found that if only query `Student `,there will be an error:`Unknown column 'StudentCourse.id' in 'field list'`, in Spring data JDBC's shoes,Entity should be complete, but I think `querydsl` is sql-oriented,only query `Student ` is reasonable.

**Comment by xjianyu** [comment]
`studentRepository.query(query -> query.select(studentRepository.entityProjection())
                                                                     .from(student)
                                                                     .where(student.name.eq("givenStudent"))
                                                                     .fetch())`

**Comment by lpandzic** [comment]
> but I think querydsl is sql-oriented,only query Student is reasonable.

Querydsl SQL module, which is used here, is sql based. In other words, it doesn't have first class support for relationships like, for example, Querydsl JPA module does.

Repository `entityProjection` contains relationships so it can be used to get data together with joined tables.
Generated QClass ignores MappedCollection fields so that one (`query.select(QStudent.student)) can be used to fetch just Student data without any joins.
This also means that you can't use in selection part of the query:
* `entityProjection` if you don't want to join data
*  `QStudent.student` if you want to join data

**Comment by xjianyu** [comment]
got it,thanks a lot.In my actual project, business entities and query entities are defined respectively, query entity does not contain relationships, only table fields. Using Querydsl SQL would be a good choice in CQRS pattern.
