### ISSUE TITLE
R2dbc Querydsl use Projections but log not print relation table

### ISSUE THREAD

**Issue by jgspark** [infobip/infobip-spring-data-querydsl#71]
hi , i use to r2dbc querydsl 

when i use to single table dynamic projections  , this is  success work  

but when i use to relationship table use to left join , this is fail work 

this querydsl code 

<img width="779" alt="스크린샷 2022-10-29 오후 10 46 37" src="https://user-images.githubusercontent.com/53357210/198835316-5a6c87cb-a1fa-4878-9d24-511a01cb057b.png">

this logs code 

<img width="1243" alt="스크린샷 2022-10-29 오후 10 46 46" src="https://user-images.githubusercontent.com/53357210/198835320-c59dd5a6-c9c5-4e7a-bfe2-ddabd32231a7.png">

this log is relationship table left join but this log not print left join 

am I using it wrong?

thanks 😀

**Comment by lpandzic** [comment]
Hm, it should work based on all info provided.
Is there any exception, stacktrace?
Can you provide entities and sql for related tables? What's inside tables at the time of execution?

**Comment by lpandzic** [comment]
Can you please provide a project that reproduces this issue?

**Comment by jgspark** [comment]
@lpandzic 

this project url is [here](https://github.com/jgspark/kotlin-webflux)

**Comment by jgspark** [comment]
@lpandzic 

This is just a question.

I ran the test case but it doesn't work.

There seems to be a dependency on the test repository, can you please check?

![스크린샷 2022-12-07 오후 1 39 35](https://user-images.githubusercontent.com/53357210/206090411-8deb7bb7-d21a-45ac-ae0e-502920c69d5c.png)

**Comment by lpandzic** [comment]
I'm having issues running your example

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initializer' defined in com.example.webflux.config.QuerydslTestConfiguration: Invocation of init method failed; nested exception is org.springframework.r2dbc.connection.init.ScriptStatementFailedException: Failed to execute SQL script statement #2 of class path resource [sql/item/schema.sql]: create table item_history ( id bigint NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, type VARBINARY(255) null, count bigint null, limit_count bigint null, created_at bigint null, CONSTRAINT item_pk PRIMARY KEY (id), constraint item_history_item_null_fk foreign key (item_id) references item (id) ); nested exception is io.r2dbc.spi.R2dbcBadGrammarException: [90045] [90045] Constraint "ITEM_PK" already exists; SQL statement:
create table item_history ( id bigint NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, type VARBINARY(255) null, count bigint null, limit_count bigint null, created_at bigint null, CONSTRAINT item_pk PRIMARY KEY (id), constraint item_history_item_null_fk foreign key (item_id) references item (id) ) [90045-214]

```

**Comment by jgspark** [comment]
@lpandzic 

I fixed that error.  Can you get a pull and check it out?

**Comment by lpandzic** [comment]
Ok, it builds and all test pass now.
Is there a test that reproduces the issue?

**Comment by jgspark** [comment]
@lpandzic 

There is no such test case.

I will leave a mention after creating a test case.

**Comment by jgspark** [comment]
@lpandzic 

This is the `findAll item and history` method in ItemQuerydslRepositoryTest.

**Comment by lpandzic** [comment]
Hm, the test still passes and I don't understand from the code what is expected to happen.

**Comment by jgspark** [comment]
This is not an error.

However, I confirmed that the join clause is not used.

I'll check more and let you know.

**Comment by lpandzic** [comment]
I'm closing this down as stale. Feel free to reopen if you can provide more info or a reproduction.
