### ISSUE TITLE
`SimpleQuerydslR2dbcFragment` always uses `TransactionalRowsFetchSpec`

### ISSUE THREAD

**Issue by davin111** [infobip/infobip-spring-data-querydsl#79]
`createQuery()` of `SimpleQuerydslR2dbcFragment` returns `new TransactionalRowsFetchSpec<>(databaseClient.sql(sql).map(mapper), TransactionalOperator.create(reactiveTransactionManager));`.

This makes any query using this method are executed with a transaction even when it is just `select` query which doesn't needs transaction practically.

Also, it uses `TransactionalOperator.create(reactiveTransactionManager)` which executes `TransactionDefinition.withDefaults()` inside. So, transactionDefinition made by outer scope can be ignored.

Did I miss something? If so, please let me know how I use this awesome library correctly.
If these operations are intended, could you explain the reason?

**Comment by lpandzic** [comment]
Hm, I don't recall anymore why transaction was created manually there but since tests pass without transaction operator, I'll assume it's safe to remove.

**Comment by lpandzic** [comment]
Released in 8.0.1
