### ISSUE TITLE
Error generating Q classes

### ISSUE THREAD

**Issue by vinodhan16** [infobip/infobip-spring-data-querydsl#87]
`**type Class does not take parameters**`

Getting this error while generating Q Classes

`    public QStudent(Class<? extends Student> type, PathMetadata metadata, PathInits inits) {
        super(type, metadata, inits);
        this.className = inits.isInitialized("className") ? new QClass(forProperty("className")) : null;
        this.section = inits.isInitialized("section") ? new QSection(forProperty("section")) : null;
    }`
    
    this is the generated code showing error

**Comment by lpandzic** [comment]
Can you provide a example test project that replicates this issue?
It's next to impossible to figure out what exactly went wrong from your message.
