### ISSUE TITLE
two entity join but when projection is null?

### ISSUE THREAD

**Issue by basquiat78** [infobip/infobip-spring-data-querydsl#91]
e.g 

```
queryDsl.query {
            it.select(Projections.constructor(MyDto::class.java,
                customer.id,
                customer.name,
                customer.createdAt,
                customer.updatedAt,
                order.id.`as`("orderId"),
                // do other 
                order.createdAt.`as`("orderAt")
                order.updatedAt.`as`("orderUpdateAt")
                )
            )
            .from(customer)
            .innerJoin(order).on(customer.id.eq(order.customerId))
            .where(customer.id.eq(id))
        }
```

error

```
org.springframework.data.mapping.model.MappingInstantiationException:
blah, blah blah,  arguments 1, john doe, 2023-06-12T10:42:23,2023-06-14T13:42:01, null, null, null
```
I  have given aliases to duplicate column names. However, when the variable names in the custom and order entities are the same, the subsequent columns appear as null.

of course, f there are no conflicting columns, the execution proceeds successfully.

What are the possible solutions I can consider to resolve this issue?

**Comment by lpandzic** [comment]
Honestly I don't use aliases, with records creating new projection types is really cheap.

**Comment by lpandzic** [comment]
Does this work with regular querydsl? I'm trying to understand whether this is a general querydsl problem or something specific to this project.

**Comment by basquiat78** [comment]
@lpandzic 

ok, I have identified the issue regarding this

this issue is due to PascalNameStrategy

Both column names and aliases are affected by this PascalNameStrategy.

```
e.g  order.createdAt.`as`("orderAt")
```

if PascalNameStrategy, aliases columName change OrderAt

if CamelNameStrategy, , aliases columName change order_at

but queryDSL with JPA,  aliase columName is 'orderAt'

Therefore, depending on the strategy used, this aspect should also be handled accordingly.

```
# if use PascalNameStrategy
e.g  order.createdAt.`as`("OrderAt")

# if use CamelNameStrategy
e.g  order.createdAt.`as`("order_at")
```

**Comment by lpandzic** [comment]
Ok, so you sorted out your problem? Nothing should be changed in the project?

**Comment by basquiat78** [comment]
@lpandzic 

Yes! But you need to guideline this issue

**Comment by lpandzic** [comment]
Can you create a PR with the fix and a test?

**Comment by lpandzic** [comment]
I'm closing this one as stale.
